PREFIX  dbo:  <http://dbpedia.org/ontology/> 
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX  dbp:  <http://dbpedia.org/property/> 
PREFIX  dct:  <http://purl.org/dc/terms/> 
PREFIX  dbc:  <http://dbpedia.org/resource/Category:> 
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX yago: <http://dbpedia.org/class/yago/>
PREFIX vrank: <http://purl.org/voc/vrank#>
 
SELECT DISTINCT  ?city_name ?sun

FROM <http://dbpedia.org> 
FROM <http://people.aifb.kit.edu/ath/#DBpedia_PageRank> 


WHERE { 
?city rdf:type yago:Capital108518505 .
?city rdfs:label   ?city_name. 
?city dbp:yearSun  ?sun.
?city vrank:hasRank ?value.

FILTER langMatches(lang(?city_name), "EN") 
} 
ORDER BY DESC (?value)
LIMIT 50